### ISSUE TITLE
Implement TDD

### ISSUE THREAD

**Issue by raheebwa** [Israel-Laguan/Private-Events#26]
- [x] Setup Test Driven Development, with Rspec and Capybara
- [x]  Add unit tests for models associations and validations (use Rspec hint)
- [x] Add integrations tests for authentication and events management (use Rspec and Capybara hint)

**Comment by TCsTheMechanic** [comment]
Can I work on Add unit tests for models associations and validations ?

**Comment by Israel-Laguan** [comment]
> Can I work on Add unit tests for models associations and validations ?

I think @raheebwa already made some but if you want you can contribute making a PR. Also please wait a little until @raheebwa push his changes. But besides that thanks for contribute!

**Comment by TCsTheMechanic** [comment]
Ok, thanks 😄
