### ISSUE TITLE
add a delete button on the events created by the user.

### ISSUE THREAD

**Issue by S-Toky** [Israel-Laguan/Private-Events#40]

**Comment by Israel-Laguan** [comment]
it needs to have a backend implementation first so frontend would just pick up. Please create an issue or a PR with the backend changes to support deleting an event.

**Comment by S-Toky** [comment]
![Capture du 2021-04-07 18-42-03](https://user-images.githubusercontent.com/52690513/113988935-9e945f80-9858-11eb-87eb-890878cc9c64.png)
this is the picture I wanted to say about the delete button, so on the back, in the controller, the delete method is already there but for the user to be able to remove an event he is the author, it must be implemented in case the user will cancel the event.

**Comment by Israel-Laguan** [comment]
Ahh perfect, if the backend have the method, please add the delete under one condition, only the creator of the event should delete it, any other one invited doesn't should be capable to delete an event

**Comment by S-Toky** [comment]
ok, I'll see that and do it

**Comment by S-Toky** [comment]
I finished coding the delete button with the conditions, I do the git push on my branch so?

**Comment by S-Toky** [comment]
it is done and pusher on the branch SToky. 
working hour 1h

**Comment by Israel-Laguan** [comment]
`SToky`  is not a good name for a branch. For this case I suggest `40-add-delete-button`. For future PRs please check this: https://deepsource.io/blog/git-branch-naming-conventions/

**Comment by S-Toky** [comment]
ok, I will make the new push with the right name

**Comment by Israel-Laguan** [comment]
Solved in #54
