### ISSUE TITLE
day's event

### ISSUE THREAD

**Issue by S-Toky** [Israel-Laguan/Private-Events#47]
add a list of events taking place on the same day, i.e. in real time. 
![Capture du 2021-04-10 11-03-35](https://user-images.githubusercontent.com/52690513/114263106-48582580-99ec-11eb-8da9-434d8efb0339.png)
add an event of the day

**Comment by Israel-Laguan** [comment]
Good to go

**Comment by S-Toky** [comment]
I finished the code and made the push 
hour of work 1h

**Comment by Israel-Laguan** [comment]
Solved in #59
